### ISSUE TITLE
Improve the recognition for English and Japanese text.

### ISSUE THREAD

**Issue by 13582351091** [ragavsachdeva/magi#4]
I found that the extraction for English text works well, but when I switch the language of the comic to Chinese or Japanese, even though the selection of dialogue boxes (highlighted in red) is correct, the ocr_results only contains strange symbols and YouTube website addresses (invalid links). How can I solve this issue?

**Comment by ragavsachdeva** [comment]
The built-in OCR model is exclusively trained on English data. You will need to use a Japanese OCR model e.g. [this one](https://huggingface.co/kha-white/manga-ocr-base).
