### ISSUE TITLE
No instruction or guidance of how to build ui or repo package to use

### ISSUE THREAD

**Issue by bosskham** [ragavsachdeva/magi#6]
Please provide the repo and corresponding instruction of how to use and and to build ui like the demo

**Comment by ragavsachdeva** [comment]
https://huggingface.co/ragavsachdeva/magi/tree/main
https://huggingface.co/ragavsachdeva/magiv2/tree/main
https://huggingface.co/spaces/ragavsachdeva/the-manga-whisperer/blob/main/app.py
https://huggingface.co/spaces/ragavsachdeva/Magiv2-Demo/blob/main/app.py
https://www.gradio.app/guides/quickstart
